name: torres
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.1.0
  animate_do: ^3.1.2


cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bmw.jpg
    - assets/bmw1.png
    - assets/chevrolet.jpg
    - assets/chevy4.png
    - assets/fondo.jpg
    - assets/honda.png
    - assets/honda1.png
    - assets/hyudai3.png
    - assets/hyundai.png
    - assets/marcas.jpg
    - assets/vw5.png
    - assets/vwlogo.jpg
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
